---
# EKS Cluster config to create private nodes with NAT Gateway

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c

iam:
  withOIDC: true

metadata:
  name: custom-vpc-cluster
  region: us-west-2
  version: "1.20"

vpc:
  cidr: 172.16.0.0/16
  autoAllocateIPv6: true
  clusterEndpoints:
    privateAccess: false
    publicAccess: true

managedNodeGroups:
  - name: nodegroup1
    instanceType: m5.xlarge
    amiFamily: "Ubuntu2004"
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "controllerManager", "authenticator"]
    logRetentionInDays: 7