---
# Basic EKS cluster configuration for a 2-node cluster through eksctl
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c

metadata:
  name: simple-cluster
  region: us-west-2
  version: "1.20"

vpc:
  cidr: 172.16.0.0/16

managedNodeGroups:
  - name: group1
    instanceType: m5.xlarge
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "controllerManager", "authenticator"]
    logRetentionInDays: 7